name: Production pipe

on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          cache: 'yarn'
      - run: yarn

  test-unit:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          cache: 'yarn'
      - run: yarn
      - run: yarn test:unit:ci

  test-e2e:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          cache: 'yarn'
      - run: yarn
      - run: yarn test:e2e:ci

  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          cache: 'yarn'
      - run: yarn
      - run: yarn build
      - name: Save dist folder
        uses: actions/upload-artifact@v2
        with:
          name: dist
          if-no-files-found: error
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: [test-unit, test-e2e, build]
    steps:
      - uses: actions/checkout@v2
      - name: Download dist folder
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - run: ls -l dist
      - run: echo "Successfully deployed!"



  
